CoreAppliction/Areas/Admin/Controllers/CategoryController.cs
using CoreAppliction.Data;
using CoreAppliction.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreAppliction.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext _db)
        {
             this._db = _db;
        }
        public async Task<IActionResult> Index()
        {
            return View(await  _db.categories.ToListAsync());
        }


    //CREATE
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _db.Add(category);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(category);
        }

    //EDIT
        public async Task<IActionResult> Edit(int? id)
        {
            if (id==null)
            {
                return RedirectToAction("Index");
            }
            var getDetails = await _db.categories.FindAsync(id);
            return View(getDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category cat)
        {
            if (ModelState.IsValid)
            {
                _db.Update(cat);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(cat);
        }

    //DETAILS
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var getDetails = await _db.categories.FindAsync(id);
            return View(getDetails);
        }


    //DELETE
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var todelete = await _db.categories.FindAsync(id);
            return View(todelete);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var todelete = await _db.categories.FindAsync(id);
            _db.categories.Remove(todelete);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

CoreAppliction/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreAppliction.Models;

namespace CoreAppliction.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _usermanager;
        public UserController(UserManager<ApplicationUser> usermanager)
        {
            _usermanager = usermanager;
        }
        public IActionResult AllUsers()
        {
            var users = _usermanager.Users;
            return View(users);
        }
    }
}

CoreAppliction/Views/Shared/View.cshtml
<p>
    <a asp-action="Create" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Create New</a>
</p>

CoreAppliction/Views/Shared/View1.cshtml
@model int

<a asp-action="Edit" asp-route-id="@Model" class="btn btn-primary"><i class="fas fa-edit"></i></a> |
<a asp-action="Details" asp-route-id="@Model" class="btn btn-success"><i class="fas fa-info-circle"></i></a> | 
<a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>

CoreAppliction/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreAppliction</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap1.css" rel="stylesheet" />
    <link href="~/css/font-awesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreAppliction</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="AllUsers">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CoreAppliction - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>